#!/usr/bin/env python3
"""Copy layer geojson, viewpoints, QML styles, and photos from new_files/ into src/assets/."""
import csv
import glob
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NEW = ROOT / "new_files"
LAYERS = ROOT / "src" / "assets" / "layers"
SECTIONS = ROOT / "src" / "assets" / "styles" / "sections"
BASE_STYLES = ROOT / "src" / "assets" / "styles"
PHOTOS = ROOT / "src" / "assets" / "photos"
OBJECT_PHOTOS = ROOT / "public" / "object_photos"
OBJECT_PHOTO_MANIFEST = ROOT / "src" / "objectPhotoManifest.ts"
LONGREAD = ROOT / "src" / "assets" / "longread"
LAYERS_CSV = ROOT / "new_legend" / "LAYERS.csv"

PHOTO_EXTS = {".png", ".jpg", ".jpeg", ".webp"}

# Not referenced by any id_map; ~948 MB — skip to keep dist lean.
SKIP_LAYER_FILES = {"isoline_2m.geojson"}

# Top-level new_files dirs that are data, not click-trigger photo stores.
SKIP_OBJECT_DIRS = {"layers", "style", "photos", "23_1", "23_2"}

# Layer style names that may have sibling photo folders at new_files/{name}/.
DEFAULT_OBJECT_FOLDERS = ("mount", "estate")


def _photo_folders_from_csv() -> set[str]:
    folders: set[str] = set(DEFAULT_OBJECT_FOLDERS)
    if not LAYERS_CSV.is_file():
        return folders
    with LAYERS_CSV.open(encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            folder = (row.get("name_folder") or "").strip()
            if folder:
                folders.add(folder)
    return folders


def _discover_object_folders() -> set[str]:
    """Any top-level dir under new_files/ that directly contains image files."""
    folders = _photo_folders_from_csv()
    if not NEW.is_dir():
        return folders
    for entry in NEW.iterdir():
        if not entry.is_dir() or entry.name in SKIP_OBJECT_DIRS:
            continue
        if any(
            child.is_file() and child.suffix.lower() in PHOTO_EXTS for child in entry.iterdir()
        ):
            folders.add(entry.name)
    return folders


def _write_object_photo_manifest(manifest: dict[str, list[str]]) -> None:
    lines = [
        "// Auto-generated by scripts/copy-new-assets.py — do not edit.",
        "export const OBJECT_PHOTO_FILES: Record<string, readonly string[]> = {",
    ]
    for folder, files in sorted(manifest.items()):
        quoted = ", ".join(f'"{name}"' for name in files)
        lines.append(f'  "{folder}": [{quoted}],')
    lines.append("} as const")
    lines.append("")
    OBJECT_PHOTO_MANIFEST.write_text("\n".join(lines), encoding="utf-8")


def _copy_object_photos() -> tuple[int, list[str]]:
    copied = 0
    copied_folders: list[str] = []
    manifest: dict[str, list[str]] = {}
    OBJECT_PHOTOS.mkdir(parents=True, exist_ok=True)
    for folder_name in sorted(_discover_object_folders()):
        src_dir = NEW / folder_name
        if not src_dir.is_dir():
            continue
        dest_dir = OBJECT_PHOTOS / folder_name
        dest_dir.mkdir(parents=True, exist_ok=True)
        folder_count = 0
        file_names: list[str] = []
        for src in sorted(src_dir.iterdir(), key=lambda p: p.name.lower()):
            if not src.is_file() or src.suffix.lower() not in PHOTO_EXTS:
                continue
            shutil.copy2(src, dest_dir / src.name)
            copied += 1
            folder_count += 1
            file_names.append(src.name)
        if folder_count:
            manifest[folder_name] = file_names
            copied_folders.append(f"{folder_name} ({folder_count})")
    _write_object_photo_manifest(manifest)
    return copied, copied_folders


LAYERS.mkdir(parents=True, exist_ok=True)
for src in glob.glob(str(NEW / "layers" / "*.geojson")):
    if Path(src).name in SKIP_LAYER_FILES:
        continue
    shutil.copy2(src, LAYERS)

viewpoints = NEW / "1" / "Viewpoints.geojson"
if viewpoints.is_file():
    shutil.copy2(viewpoints, LAYERS / "Viewpoints.geojson")

SECTIONS.mkdir(parents=True, exist_ok=True)
for src in glob.glob(str(NEW / "style" / "*.qml")):
    shutil.copy2(src, SECTIONS)

for name in ("isoline_5m.qml", "sectors_level.qml", "amphitheater_bound.qml"):
    qml = NEW / "style" / name
    if qml.is_file():
        shutil.copy2(qml, BASE_STYLES / name)

# Longread media → src/assets/photos (flat files only).
PHOTOS.mkdir(parents=True, exist_ok=True)
LONGREAD.mkdir(parents=True, exist_ok=True)
photos_dir = NEW / "photos"
copied_photos = 0
if photos_dir.is_dir():
    for src in photos_dir.iterdir():
        if src.is_file() and src.suffix.lower() in PHOTO_EXTS:
            shutil.copy2(src, PHOTOS / src.name)
            shutil.copy2(src, LONGREAD / src.name)
            copied_photos += 1

copied_object_photos, object_folders = _copy_object_photos()

print("Copied layers:", len(glob.glob(str(LAYERS / "*.geojson"))))
print("Copied section qml:", len(glob.glob(str(SECTIONS / "*.qml"))))
print("Copied photos:", copied_photos, "->", PHOTOS.relative_to(ROOT))
print(
    "Copied object photos:",
    copied_object_photos,
    "->",
    OBJECT_PHOTOS.relative_to(ROOT),
    "|",
    ", ".join(object_folders) if object_folders else "(none)",
)
