#!/usr/bin/env python3
"""Generate src/layerUrls.ts — URL map for geojson files referenced at runtime.

Sources of referenced layer names:
  - section-overlays.json  → every overlay layer + Phase-2 inscription /
    folder_vector point layers.
  - base-composition.json  → base vector layers.
  - LONGREAD.csv `Zoom`    → scroll-zoom extent layers (e.g. historical_zones_*).
  - EXTRA_FILES            → explore-mode sector highlight + global viewpoints.

Only files that actually exist under src/assets/layers are emitted, so the
generator never produces broken `new URL(...)` references. Run AFTER
copy-new-assets.py so freshly-copied geojson are present.
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OVERLAYS = ROOT / "src" / "assets" / "sections" / "section-overlays.json"
BASE = ROOT / "src" / "assets" / "styles" / "base-composition.json"
LONGREAD = ROOT / "new_legend" / "LONGREAD.csv"
LAYERS_DIR = ROOT / "src" / "assets" / "layers"
OUT = ROOT / "src" / "layerUrls.ts"

# Explore-mode sector highlight + global viewpoints (not in section-overlays sets).
EXTRA_FILES = ["Viewpoints.geojson", "sector.geojson", "21_живопись.geojson"]


def overlay_names() -> set[str]:
    names: set[str] = set()
    data = json.loads(OVERLAYS.read_text(encoding="utf-8"))
    for layer_set in data["sets"].values():
        for layer in layer_set.get("layers", []):
            names.add(layer["name"])
        # Phase-2 point/centroid layers also need URLs so they can be loaded.
        for insc in layer_set.get("inscriptions", []):
            names.add(insc["name"])
        for fv in layer_set.get("folder_vectors", []):
            names.add(fv["folder_vector"])
    return names


def base_names() -> set[str]:
    names: set[str] = set()
    base = json.loads(BASE.read_text(encoding="utf-8"))
    for entry in base["render_order"]:
        if entry.get("kind") == "vector":
            names.add(entry["geojson"].removesuffix(".geojson"))
    return names


def zoom_names() -> set[str]:
    names: set[str] = set()
    with LONGREAD.open(encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            z = (row.get("Zoom") or "").strip()
            if z:
                names.add(z)
    return names


def main() -> None:
    names = overlay_names() | base_names() | zoom_names()
    candidates = sorted(f"{name}.geojson" for name in names) + EXTRA_FILES

    seen: set[str] = set()
    unique_files: list[str] = []
    missing: list[str] = []
    for file_name in candidates:
        if file_name in seen:
            continue
        seen.add(file_name)
        if (LAYERS_DIR / file_name).is_file():
            unique_files.append(file_name)
        else:
            missing.append(file_name)

    lines = [
        "// Auto-generated by scripts/gen-layer-urls.py — do not edit.",
        "",
        "export const LAYER_URL_BY_FILE: Record<string, string> = {",
    ]
    for file_name in unique_files:
        lines.append(
            f'  "{file_name}": new URL("./assets/layers/{file_name}", import.meta.url).href,'
        )
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(unique_files)} layer URLs -> {OUT.relative_to(ROOT)}")
    if missing:
        print("Skipped (not found in src/assets/layers):", ", ".join(missing))


if __name__ == "__main__":
    main()
