#!/usr/bin/env python3
"""Generate src/assets/styles/base-composition.json from new_legend/BASE_MAP.csv.

Comma-delimited CSV (only id_map=1 today):
  id_map, id_layer_click, name_layer_base, type_layer, <blank>, raster_style

Faithful transform notes (see agentic_dev/new-legend-TZ.md §1.2):
  - `type_layer` is unreliable for the rasters (it says tif/geojson). The two
    raster layers are recognised by name and emitted as raster-tile sources:
      * `positron с подписями` → CARTO Positron *with* labels (XYZ).
      * `relief_water1`        → pre-baked relief+water pyramid (TMS).
  - `raster_style=55` → raster-opacity 0.55.
  - the remaining rows (isoline_5m, sectors_level, amphitheater_bound) are
    geojson vectors; their paint is ported from the calibrated Phase-0 values.
  - BASE_MAP layers are non-clickable and carry no legend rows.

Render order follows id_layer_click ascending (bottom → top).
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "new_legend" / "BASE_MAP.csv"
OUT_PATH = ROOT / "src" / "assets" / "styles" / "base-composition.json"

# Raster sources keyed by name_layer_base (CSV carries no URL/scheme).
RASTER_CONFIG = {
    "positron с подписями": {
        "name": "positron_labels",
        "source": "https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png",
        "absolute_url": True,
        "minzoom": 0,
        "maxzoom": 19,
        "attribution": "© OpenStreetMap contributors © CARTO",
    },
    "relief_water1": {
        "name": "relief_water1",
        "source": "relief_water1/{z}/{x}/{y}.png",
        "scheme": "tms",
        "minzoom": 10,
        "maxzoom": 14,
    },
}

# Calibrated geojson vector paint (ported from the Phase-0 base composition).
VECTOR_STYLE = {
    "isoline_5m": {"line": {"color": "rgb(225,89,137)", "width_px": 1.0}},
    "sectors_level": {
        "outline": {"color": "rgb(0,0,0)", "width_px": 1.0, "opacity": 1.0, "dasharray": [4, 2]}
    },
    "amphitheater_bound": {"line": {"color": "rgb(67,69,69)", "width_px": 1.4}},
}


def main() -> None:
    rows: list[dict] = []
    with CSV_PATH.open(encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f)
        header = next(reader)  # id_map,id_layer_click,name_layer_base,type_layer,,raster_style
        for raw in reader:
            if not any(cell.strip() for cell in raw):
                continue
            rows.append(
                {
                    "id_map": raw[0].strip(),
                    "order": int((raw[1] or "0").strip() or 0),
                    "name": raw[2].strip(),
                    "type": raw[3].strip(),
                    "raster_style": (raw[5].strip() if len(raw) > 5 else ""),
                }
            )

    rows.sort(key=lambda r: r["order"])

    render_order: list[dict] = []
    for r in rows:
        name = r["name"]
        if name in RASTER_CONFIG:
            cfg = dict(RASTER_CONFIG[name])
            entry: dict = {"kind": "raster", **cfg}
            if r["raster_style"]:
                entry["opacity"] = round(int(r["raster_style"]) / 100, 2)
            render_order.append(entry)
        else:
            entry = {"kind": "vector", "name": name, "geojson": f"{name}.geojson"}
            if name in VECTOR_STYLE:
                entry["style"] = VECTOR_STYLE[name]
            render_order.append(entry)

    manifest = {
        "_comment": "Base composition generated by scripts/gen-base-map.py from new_legend/BASE_MAP.csv (id_map=1). Single global basemap stack: Positron+labels, relief_water1@55%, then calibrated geojson vectors. Non-clickable, no legend.",
        "id_layer_base": 1,
        "render_order": render_order,
        "px_per_mm_assumption": 2.83,
    }

    OUT_PATH.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)} with {len(render_order)} layers")


if __name__ == "__main__":
    main()
