#!/usr/bin/env python3
"""Generate src/layerUrls.ts — URL map for geojson files referenced by manifests only."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OVERLAYS = ROOT / "src" / "assets" / "sections" / "section-overlays.json"
BASE = ROOT / "src" / "assets" / "styles" / "base-composition-1.json"
OUT = ROOT / "src" / "layerUrls.ts"

# Explore-mode sector highlight + global viewpoints (not in section-overlays sets).
EXTRA_FILES = ["Viewpoints.geojson", "sector.geojson"]


def layer_names() -> set[str]:
    names: set[str] = set()
    with OVERLAYS.open(encoding="utf-8") as f:
        data = json.load(f)
    for layer_set in data["sets"].values():
        for layer in layer_set.get("layers", []):
            names.add(layer["name"])
    with BASE.open(encoding="utf-8") as f:
        base = json.load(f)
    for entry in base["render_order"]:
        if entry.get("kind") == "vector":
            names.add(entry["geojson"].removesuffix(".geojson"))
    return names


def main() -> None:
    files = sorted(f"{name}.geojson" for name in layer_names()) + [
        f for f in EXTRA_FILES if f not in {f"{n}.geojson" for n in layer_names()}
    ]
    # Deduplicate while preserving order
    seen: set[str] = set()
    unique_files: list[str] = []
    for f in files:
        if f not in seen:
            seen.add(f)
            unique_files.append(f)

    lines = [
        "// Auto-generated by scripts/gen-layer-urls.py — do not edit.",
        "",
        "export const LAYER_URL_BY_FILE: Record<string, string> = {",
    ]
    for file_name in unique_files:
        lines.append(
            f'  "{file_name}": new URL("./assets/layers/{file_name}", import.meta.url).href,'
        )
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(unique_files)} layer URLs -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
