// Base-layer composition derived from `src/assets/styles/base-composition.json`
// (the runtime-readable port of `new_legend/BASE_MAP.csv`, generated by
// `scripts/gen-base-map.py`). The new legend defines a single global basemap
// (id_layer_base=1): Positron+labels, relief_water1@55%, then calibrated
// geojson vectors. The 1|2|3 keying is kept for type compatibility with the
// longread model's `base_id`, but every section currently resolves to base #1.

import baseCompositionManifest from './assets/styles/base-composition.json'

export const TILE_BASE_URL =
  import.meta.env.VITE_TILE_BASE_URL ??
  'https://spbmlaplus.github.io/spb_mountains_tiles'

export type RasterEntry = {
  kind: 'raster'
  id: string
  urlTemplate: string
  minzoom?: number
  maxzoom?: number
  opacity?: number
  paint?: Record<string, unknown>
  attribution?: string
  scheme?: 'xyz' | 'tms'
}

export type VectorEntry = {
  kind: 'vector'
  file: string
  style: string
}

export type BaseComposition = (RasterEntry | VectorEntry)[]

type ManifestRasterEntry = {
  kind: 'raster'
  name: string
  source: string
  absolute_url?: boolean
  scheme?: 'xyz' | 'tms'
  minzoom?: number
  maxzoom?: number
  opacity?: number
  paint?: Record<string, unknown>
  attribution?: string
}

type ManifestVectorEntry = {
  kind: 'vector'
  name: string
  geojson: string
}

type ManifestEntry = ManifestRasterEntry | ManifestVectorEntry

type Manifest = { render_order: ManifestEntry[] }

const compositionFromManifest = (manifest: Manifest): BaseComposition =>
  manifest.render_order.map((entry) => {
    if (entry.kind === 'raster') {
      const relativePath = entry.source.replace(/^tiles\//, '')
      const urlTemplate = entry.absolute_url
        ? entry.source
        : `${TILE_BASE_URL}/${relativePath}`
      return {
        kind: 'raster',
        id: entry.name,
        urlTemplate,
        minzoom: entry.minzoom ?? 10,
        maxzoom: entry.maxzoom ?? 14,
        opacity: entry.opacity,
        paint: entry.paint,
        attribution: entry.attribution ?? '© Горные просторы',
        scheme: entry.scheme,
      }
    }
    return {
      kind: 'vector',
      file: entry.geojson,
      style: entry.name,
    }
  })

const baseComposition = compositionFromManifest(baseCompositionManifest as Manifest)

export const BASE_COMPOSITIONS: Record<1 | 2 | 3, BaseComposition> = {
  1: baseComposition,
  2: baseComposition,
  3: baseComposition,
}

export const DEFAULT_BASE_ID: 1 | 2 | 3 = 1
