// Click-trigger photos served from `public/object_photos/{folder}/…` (not bundled).
// Manifest: `objectPhotoManifest.ts` (generated by scripts/copy-new-assets.py).
//   mount/estate: `{id}_1.ext`, `{id}_2.ext`
//   21, 1, …: `{id}.ext` or `{name}.ext` (single image per object)
// Legacy mount bundle: `mountain_images/{id}.webp` (small set, still bundled).

import { OBJECT_PHOTO_FILES } from './objectPhotoManifest'
import { viewpointPhotoUrl } from './viewpointPhotos'

const PHOTO_BASE = `${import.meta.env.BASE_URL}object_photos`

const legacyPhotoModules = import.meta.glob('./assets/mountain_images/*.webp', {
  query: '?url',
  import: 'default',
  eager: true,
}) as Record<string, string>

const fileIndex = new Map<string, string>()
for (const [folder, files] of Object.entries(OBJECT_PHOTO_FILES)) {
  for (const fileName of files) {
    const base = fileName.replace(/\.[^.]+$/, '')
    fileIndex.set(`${folder}/${base}`, fileName)
  }
}

const photoUrlFor = (folder: string, base: string): string | null => {
  const fileName = fileIndex.get(`${folder}/${base}`)
  if (!fileName) return null
  return `${PHOTO_BASE}/${folder}/${encodeURIComponent(fileName)}`
}

export const objectPhotoUrl = (
  folder: string,
  photoKey: string | number,
  slot: 1 | 2,
): string | null => photoUrlFor(folder, `${String(photoKey)}_${slot}`)

/** @deprecated Use objectPhotoUrl — kept for legacy mountain_images webp pairs. */
export const legacyMountainPhotoUrl = (
  id: string,
  variant: 'full' | 'thumb' = 'full',
): string | null => {
  const suffix = variant === 'thumb' ? '.thumb' : ''
  return legacyPhotoModules[`./assets/mountain_images/${id}${suffix}.webp`] ?? null
}

export const resolveObjectPhotoUrl = (
  folder: string,
  photoKey: string | number,
  slot: 1 | 2,
): string | null => {
  const key = String(photoKey)
  const slotted = objectPhotoUrl(folder, key, slot)
  if (slotted) return slotted
  // Single-file folders (21, 1, …): `{id}.jpg` counts as photo slot 1.
  if (slot === 1) {
    const single = photoUrlFor(folder, key)
    if (single) return single
    // id_map 23 viewpoint photos (folder "1") share Viewpoints archive.
    if (folder === '1') {
      const vp = viewpointPhotoUrl(key)
      if (vp) return vp
    }
  }
  if (folder === 'mount') {
    const legacyId = key.padStart(4, '0')
    return legacyMountainPhotoUrl(legacyId, slot === 1 ? 'thumb' : 'full')
  }
  return null
}

export const hasObjectPhoto = (
  folder: string,
  photoKey: string | number | null | undefined,
  slot: 1 | 2,
): boolean =>
  photoKey !== null &&
  photoKey !== undefined &&
  resolveObjectPhotoUrl(folder, photoKey, slot) !== null

export type GalleryPhoto = { id: string; url: string; fileName: string }

/** All photos in a folder — used by id_map 21 gallery (no geojson layer). */
export const getObjectPhotoGallery = (folder: string): GalleryPhoto[] => {
  const files = OBJECT_PHOTO_FILES[folder] ?? []
  return files
    .map((fileName) => {
      const id = fileName.replace(/\.[^.]+$/, '')
      return {
        id,
        fileName,
        url: `${PHOTO_BASE}/${folder}/${encodeURIComponent(fileName)}`,
      }
    })
    .sort((a, b) => {
      const na = Number(a.id)
      const nb = Number(b.id)
      if (Number.isFinite(na) && Number.isFinite(nb)) return na - nb
      return a.id.localeCompare(b.id, undefined, { numeric: true })
    })
}
